### ISSUE TITLE
Support the specification of a directory containing the gatorgrade.yml file

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrade-action#2]
Hello @mariakimheinert and @Michionlion and @burgess01!

Thanks for your work on this GitHub Action, I really appreciate it.

I noticed that in the documentation and in the actual implementation of this GitHub Action it seems as though you cannot specify the directory that contains the `gatorgrade.yml` file. For instance, the following example does not allow the specification of a `directory` that would contain the `gatorgrade.yml` file. Would this be possible to add? Thanks for any suggestions that you have!

```
name: Grader
on: [push]
jobs:
    grade:
        run-on: ubuntu-latest
        steps:
            - name: Checkout repository
                uses: actions/checkout@v2
            - name: Run Gatorgrade
                uses: GatorEducator/gatorgrade-action@v1
```
